### ISSUE TITLE
Plan of PyTorch version?

### ISSUE THREAD

**Issue by RusticKey** [razvanmarinescu/brgm#1]
Hello, your work is very interesting and the Tensorflow implementation is fine. However, I am wondering if you guys have any plans of porting it into PyTorch or already having plans of releasing it? Thanks!

**Comment by razvanmarinescu** [comment]
Yes! NVIDIA just released StyleGAN-ADA in Pytorch, so we'll port straight to that! We have some deadlines coming up in the next 2-3 weeks, but we will work on it afterwards.

**Comment by RusticKey** [comment]
I see, thank you for the response and good luck! I am looking forward for the PyTorch version since most of our lab's projects are written in PyTorch.

**Comment by razvanmarinescu** [comment]
We have just released the PyTorch version here: https://github.com/razvanmarinescu/brgm-pytorch 

In the PyTorch version, we also switched to StyleGAN-ADA, and further added a Variational Inference extension for sampling from the posterior.
